"""user_login

Revision ID: 318ecc9a914e
Revises: 
Create Date: 2018-09-02 13:42:38.452826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318ecc9a914e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_user_name'), 'user_login', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_login_user_name'), table_name='user_login')
    op.drop_table('user_login')
    # ### end Alembic commands ###
